### ISSUE TITLE
Browser changes not reflected when using a bubble

### ISSUE THREAD

**Issue by Gravataz** [heilig-defense/browser-bubble#1]
I am using the trial  software and both Edge and Brave browsers, I noticed that if I make changes to a browser  running normally (non-bubbled) like add a bookmark or extension the next time I open it in a bubble those changes do not exist.

It is almost as if the bubble software captured the browsers state upon installing it  and will only launch it in that state, where no updates or changes can be made to the bubbled version.

**Comment by heilig-defense** [comment]
Did you create a Bubble shortcut of a running Bubble?  If so, that Bubble is a snapshot of the original profile at the time it was first run.  Changes made in the Bubble will persist in the Bubble but changes to the original non-Bubble profile will not be reflected. 

If you are making changes to a non-Bubble profile, you may need to close the browser so they get written to disk (not entirely sure about this but possible) so when you launch a Bubble it will be able to copy the browser data into the Bubble.

**Comment by Gravataz** [comment]
Still have not got it working right Brave will not load extensions, I have deleted bubbles made new bubbles rebooted everything short of re-installing the bubble software.

I also found a new problem, I created new bubble, and made a new bubble short cut and unchecked "Automatic Bubbleizse enabled browsers"  So only browsers can be bubbled though the app or the short cut but launching them via the app or the short cut does not bubble them.

No border color can be seen to verify bubble, you can add bookmarks , extensions etc... shut it down, open the browser outside the bubble  and all the changes are there when they should have been deleted upon exit which I have checked.

**Comment by Gravataz** [comment]
FYI:  one more thing I found, I created a new action, tested it using the test button and works fine, I try to modify or create a new bubble to use this action, the drop down finds it and put a check box but it does not get saved to the bubble and when I go back to modify that bubble it that drop down is blank and box unchecked.

However I still have it in my action list.
