### ISSUE TITLE
Can't add DNS addresses and one browser will not bubble

### ISSUE THREAD

**Issue by Gravataz** [heilig-defense/browser-bubble#7]
Everything is working much better,  extension will load in Brave Browser Bubbled but came across another possible bug.

When I try to add a  new DNS server I can add the name and country but it will not let me add an IP address.

I also use Epic Privacy Browser which is Chromium based,  Browser Bubble does not find it during install but when I add it it finds the Epic exe,  I  tried using Chromium  selection and pointed the path to the epic privacy browser\user data\.

When I launch the bubble the Epic  Browser launches but is not bubbled and am not sure why?

**Comment by heilig-defense** [comment]
DNS issue will be fixed in next release.  

Browser Bubble has built-in detections for these browsers:  Firefox, Blisk, Brave, Chrome, Chromium, Edge, Iron, Opera, Vivaldi, and Iridium.  Others, like Epic, won't be initially found but looks like that even when configured it is not recognizing it.

**Comment by heilig-defense** [comment]
We just released v1.2021.315.2050 that fixes a number of issues.  

And while we added support for Epic we also removed support for 32-bit browsers (which Epic still is for some reason).  We emailed the Epic team to ask if they could start releasing a 64-bit version.  Hopefully they will at some point in the near future.
